site_name: "Evaluation module for Survey Assist"
nav:
  - Home: index.md
  - Data Eggress: data_egress.md
  - Evaluation Metrics: evaluation_metrics.md
theme:
  name: material  # Optional, you can change it
